
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'B COLOR COLOR_TYPE F L LBRACKET NUMBER PEN R RBRACKETexpression : L NUMBER LBRACKET expression RBRACKETexpression : L NUMBER LBRACKET expression expression RBRACKETexpression : L NUMBER LBRACKET instructions RBRACKETexpression : L NUMBER LBRACKET instructions RBRACKET instructionsinstructions : instruction instructioninstruction :  F NUMBER R NUMBER \n                        | B NUMBER R NUMBER\n                        | PEN NUMBER\n                        | COLOR COLOR_TYPE\n                        | R NUMBER \n                        | F NUMBER\n                        | B NUMBER\n                        \n                      '
    
_lr_action_items = {'L':([0,4,5,14,15,16,17,18,19,20,21,22,23,26,27,],[2,2,2,-1,-3,-5,-11,-10,-12,-8,-9,-2,-4,-6,-7,]),'$end':([1,14,15,16,17,18,19,20,21,22,23,26,27,],[0,-1,-3,-5,-11,-10,-12,-8,-9,-2,-4,-6,-7,]),'NUMBER':([2,8,9,10,11,24,25,],[3,17,18,19,20,26,27,]),'LBRACKET':([3,],[4,]),'F':([4,7,15,17,18,19,20,21,26,27,],[8,8,8,-11,-10,-12,-8,-9,-6,-7,]),'B':([4,7,15,17,18,19,20,21,26,27,],[10,10,10,-11,-10,-12,-8,-9,-6,-7,]),'PEN':([4,7,15,17,18,19,20,21,26,27,],[11,11,11,-11,-10,-12,-8,-9,-6,-7,]),'COLOR':([4,7,15,17,18,19,20,21,26,27,],[12,12,12,-11,-10,-12,-8,-9,-6,-7,]),'R':([4,7,15,17,18,19,20,21,26,27,],[9,9,9,24,-10,25,-8,-9,-6,-7,]),'RBRACKET':([5,6,13,14,15,16,17,18,19,20,21,22,23,26,27,],[14,15,22,-1,-3,-5,-11,-10,-12,-8,-9,-2,-4,-6,-7,]),'COLOR_TYPE':([12,],[21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,5,],[1,5,13,]),'instructions':([4,15,],[6,23,]),'instruction':([4,7,15,],[7,16,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> L NUMBER LBRACKET expression RBRACKET','expression',5,'p_expression_loop_type1','automata.py',159),
  ('expression -> L NUMBER LBRACKET expression expression RBRACKET','expression',6,'p_expression_loop_type2','automata.py',166),
  ('expression -> L NUMBER LBRACKET instructions RBRACKET','expression',5,'p_expression_loop_type3','automata.py',172),
  ('expression -> L NUMBER LBRACKET instructions RBRACKET instructions','expression',6,'p_expression_loop_type4','automata.py',178),
  ('instructions -> instruction instruction','instructions',2,'p_instruc_instruc','automata.py',184),
  ('instruction -> F NUMBER R NUMBER','instruction',4,'p_instruction','automata.py',194),
  ('instruction -> B NUMBER R NUMBER','instruction',4,'p_instruction','automata.py',195),
  ('instruction -> PEN NUMBER','instruction',2,'p_instruction','automata.py',196),
  ('instruction -> COLOR COLOR_TYPE','instruction',2,'p_instruction','automata.py',197),
  ('instruction -> R NUMBER','instruction',2,'p_instruction','automata.py',198),
  ('instruction -> F NUMBER','instruction',2,'p_instruction','automata.py',199),
  ('instruction -> B NUMBER','instruction',2,'p_instruction','automata.py',200),
]
